DROP
    SCHEMA
    IF
        EXISTS PUBLIC CASCADE;

CREATE
    SCHEMA PUBLIC;

-- -----------------------------------------------------------------------------------------tables

-- source
CREATE TABLE "public"."source"
(
    "id"                INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "key"               VARCHAR(36),
    "created_at"        TIMESTAMP,
    "updated_at"        TIMESTAMP,
    "last_build_date"   TIMESTAMP,
    "crawl_key"         VARCHAR(36),
    "name"              VARCHAR(1024),
    "url"               VARCHAR(1024),
    "original_url"      VARCHAR(1024),
    "rss_url"           VARCHAR(1024),
    "icon_16_url"       VARCHAR(1024),
    "icon_16_path"      TEXT,
    "icon_32_url"       VARCHAR(1024),
    "icon_32_path"      TEXT,
    "icon_largest_url"  VARCHAR(1024),
    "icon_largest_path" TEXT,
    "status"            VARCHAR(1024),
    PRIMARY KEY ("id"),
    CONSTRAINT "source_key" UNIQUE ("key"),
    CONSTRAINT "source_url" UNIQUE ("url")
);

-- article
CREATE TABLE "public"."article"
(
    "id"               INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "key"              VARCHAR(36),
    "created_at"       TIMESTAMP,
    "updated_at"       TIMESTAMP,
    "crawl_key"        VARCHAR(36),
    "source_key"       VARCHAR(36),
    "title"            VARCHAR(1024),
    "url"              VARCHAR(1024),
    "original_url"     VARCHAR(1024),
    "summary"          TEXT,
    "original_summary" TEXT,
    "published_date"   TIMESTAMP,
    "image_url"        VARCHAR(1024),
    "image_path"       TEXT,
    "image_alt"        TEXT,
    "status"           VARCHAR(1024),
    PRIMARY KEY ("id"),
    CONSTRAINT "article_key" UNIQUE ("key"),
    CONSTRAINT "article_url" UNIQUE ("url")
);

-- crawl
CREATE TABLE "public"."crawl"
(
    "id"         INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "key"        VARCHAR(36),
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    PRIMARY KEY ("id"),
    CONSTRAINT "crawl_key" UNIQUE ("key")
);

--  log
CREATE TABLE "public"."log"
(
    "id"          INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "key"         VARCHAR(36),
    "created_at"  TIMESTAMP,
    "updated_at"  TIMESTAMP,
    "crawl_key"   VARCHAR(36),
    "url"         TEXT,
    "source_url"  TEXT,
    "article_url" TEXT,
    "log_type"    VARCHAR(1024),
    "error_type"  VARCHAR(1024),
    "message"     TEXT,
    "timestamp"   TIMESTAMP,
    PRIMARY KEY ("id"),
    CONSTRAINT "log_key" UNIQUE ("key")
);

-- ----------------------------------------------------------------------------------------- procedures and triggers

CREATE
    OR REPLACE
    PROCEDURE "public"."create_trigger_for_tables"() AS
$BODY$
DECLARE
    T record;
BEGIN FOR T IN
    SELECT tbl."table_name"   AS "name",
           tbl."table_schema" AS "schema"
    FROM information_schema.COLUMNS AS col
             JOIN information_schema.tables AS tbl ON tbl."table_name" = col."table_name"
    WHERE COLUMN_NAME = 'updated_at'
      AND tbl.table_type = 'BASE TABLE' LOOP
        EXECUTE format('CREATE OR REPLACE TRIGGER trigger_updated_timestamp
			BEFORE INSERT OR UPDATE ON %I.%I
		FOR EACH ROW EXECUTE PROCEDURE "public".updated_timestamp()', T.SCHEMA, T.NAME);

    END loop;
FOR T IN
    SELECT tbl."table_name"   AS "name",
           tbl."table_schema" AS "schema"
    FROM information_schema.COLUMNS AS col
             JOIN information_schema.tables AS tbl ON tbl."table_name" = col."table_name"
    WHERE COLUMN_NAME = 'created_at'
      AND tbl.table_type = 'BASE TABLE' LOOP
        EXECUTE format('CREATE OR REPLACE TRIGGER trigger_created_timestamp
		BEFORE INSERT ON %I.%I
	FOR EACH ROW EXECUTE PROCEDURE "public".created_timestamp()', T.SCHEMA, T.NAME);

    END loop;
FOR T IN
    SELECT tbl."table_name"   AS "name",
           tbl."table_schema" AS "schema"
    FROM information_schema.COLUMNS AS col
             JOIN information_schema.tables AS tbl ON tbl."table_name" = col."table_name"
    WHERE COLUMN_NAME = 'key'
      AND tbl.table_type = 'BASE TABLE' LOOP
        EXECUTE format('CREATE OR REPLACE TRIGGER trigger_key_generate
		BEFORE INSERT ON %I.%I
	FOR EACH ROW EXECUTE PROCEDURE "public".key_generate()', T.SCHEMA, T.NAME);

    END loop;

END $BODY$ LANGUAGE plpgsql;

-- created_timestamp
CREATE OR REPLACE FUNCTION "public"."created_timestamp"()
    RETURNS "pg_catalog"."trigger" AS
$BODY$
BEGIN
    NEW.created_at = CURRENT_TIMESTAMP AT TIME ZONE 'UTC';
    RETURN NEW;
END;
$BODY$ LANGUAGE plpgsql;

-- updated_timestamp
CREATE OR REPLACE FUNCTION "public"."updated_timestamp"()
    RETURNS "pg_catalog"."trigger" AS
$BODY$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP AT TIME ZONE 'UTC';
    RETURN NEW;
END;
$BODY$ LANGUAGE plpgsql;


-- key_generate
CREATE
    OR REPLACE
    FUNCTION "public"."key_generate"() RETURNS "pg_catalog"."trigger" AS
$BODY$
BEGIN IF
    NEW."key" IS NULL THEN
    NEW."key" = gen_random_uuid();

END IF;
RETURN NEW;

END;
$BODY$ LANGUAGE plpgsql;
-------------------------------------------------------------------------------------------------
CALL "public"."create_trigger_for_tables"();
-------------------------------------------------------------------------------------------------
-- List of updates applied to database before implementing versioning
ALTER TABLE article ADD COLUMN "image_path_2x" TEXT DEFAULT NULL;
ALTER TABLE source ADD COLUMN "type" TEXT DEFAULT NULL;
CREATE VIEW database_info AS SELECT 0 AS version;